login and CLI working
login and CLI required some reordering and addition of objects in correct places

resolved errors
`greeting': undefined method `username' for nil:NilClass (NoMethodError)

 `login': undefined local variable or method `greet_user' for #<CLI:0x00007f1ed2969ef0 @user=#<User:0x00007f1ed2968d20 @username="john123", @password="$2a$12$p3KoerPV/6SV5zrRS2P5h.1HFkgobNRYBM40lE23kczpwKsYPZf1O", @id=1>> (NameError)